language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "stable"
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
before_script:
  - npm start &
  - sleep 3
after_script:
  - bash <(curl -s https://codecov.io/bash)
script:
  - npm run test:coverage