language: node_js
node_js:
  - "0.12"
sudo: false
cache:
  directories:
    - node_modules
    - bower_components
script:
  - npm run test-ci
  - ./node_modules/coveralls/bin/coveralls.js < ./reporters/lcov.info
