language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "stable"
sudo: false
env:
  - TEST_TYPE=codestyle CACHE_NAME=JOB1
  - TEST_TYPE=all CACHE_NAME=JOB2
before_install:
  - stty cols 80
dist: trusty
sudo: required
addons:
  firefox: latest
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - npm run test:$TEST_TYPE -s