language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "stable"
sudo: false
env:
  - TEST_TYPE=codestyle CACHE_NAME=JOB1
  - TEST_TYPE=unit CACHE_NAME=JOB2
script:
  - npm run test:$TEST_TYPE -s