language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "stable"
sudo: false
env:
  - TEST_TYPE=codestyle CACHE_NAME=JOB1
  - TEST_TYPE=all CACHE_NAME=JOB2
before_script:
  - npm start &
script:
  - npm run test:$TEST_TYPE -s