language: node_js
node_js:
  - "6"
sudo: false
cache:
  directories:
    - node_modules
script:
  - npm run test:coverage -s
  - npm run test:codestyle -s
  - npm run test:deps -s
after_success:
  - bash <(curl -s https://codecov.io/bash)
