language: node_js
sudo: false
cache:
  directories:
    - node_modules
    - bower_components
script:
  - npm test -- --reporters=coverage,mocha
  - ./node_modules/codeclimate-test-reporter/bin/codeclimate.js < ./reporters/lcov.info
